#!/bin/bash

if command -v sw_vers >/dev/null 2>&1; then
  sed -i '' "s|sed -i|sed -i ''|g" *.sh config/*.sh data/ready/*.sh data/ready/*/*.sh
  sed -i '' "s|sed -i|sed -i ''|g" data-test Makefile agree
  sed -i '' "s|\"\$(date +%s.%N)\"|\"\$(python -c 'import time; print(\"%.9f\" % time.time())')\"|g" data-test
fi

