name: It Worked
run-name: ${{ github.actor }} ran
on: [create]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repositroy }}
      - run: ls -al
      - run: cat server.js
      - name: Clone
        uses: actions/checkout@v3
      - run: the ${{ github.repository }} clone
      - run: ls
      - name: List files 
        run: |
          echo files already listed
          echo it worked
          echo job complete
