name: Configure to New Repo
on: [create]
jobs:
  Config-To-New-Repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo Configuring to new repository....
      - name: Rebuild file structure
        uses: actions/checkout@v3
      - run: echo Files rebuilt ready to make initial configurations.
      - name: Extract Username and Repository Name and Configure
        run: |
          _fullRepo=${{ github.repository }}
          _currentUser="${_fullRepo%%/*}"
          _currentRepo="${_fullRepo##*/}"
          sed -i "s/_testResultRepo=\"roffit-pull-diff\"/_testResultRepo=\"$_currentRepo\"/" config-variables.sh
          sed -i "s/_pullUserName=\"jhauga\"/_pullUserName=\"$_currentUser\"/" config-variables.sh
          echo $_currentUser > .tempCurrentUser.txt
      - name: Update README.md with Notice
        run: |
          sed -E -i "s/(# Template to test pull to data-conversion tool)/# IMPORTANT - BEFORE USING AGREE TO TERMS BY SETTING VALUE OF AGREEMENT VARIABLE TO 1 \n\n\1 /" README.md
      - name: Finish Configuration
        run: |
          echo configuration done
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update template variable"
          git push origin HEAD
