name: It worked
run-name: ${{ github.actor }} ran
on: [create]
jobs:
  It-Worked-vanilla:
    runs-on: ubuntu-latest
    steps:      
      - run: ls
      - run: echo it 
      - name: checkout
        uses: actions/checkout@v3
      - run: echo w
      - run: _or=or
      - name: Pipe
        run: |
          echo $_or
          _k=k
          echo $_k
      - name: make complete sentence
        run: |
          echo e
          _d=d
      - name: no pipe
      - run: echo $_d
      - run: echo .
      - name: Finish
      - run: echo did it work? Check files first.
      - name: pipe again
        run: |
          ls -a
          echo looks good.
          ps ax
          echo looks good.
          ls -la
          echo good
          echo It did work.
      - name: finish
      - run: echo next no hand holding run.
