name: It worked
run-name: ${{ github.actor }} ran
on: [create]
jobs:
  It-Worked-Vanilla:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - run: echo it 
      - name: Clone
        uses: actions/checkout@v3
      - run: echo w      
      - run: echo or 
      - run: echo k
      - run: echo ed
      - run: echo .
      - run: echo Now to finish.
      - name: Finish      
        run: |
          echo did it work? Check files first.
          ls -a
          echo looks good.
          ps ax
          echo looks good.
          ls -la
          echo good
          echo It did work.
