name: Setup Codespace Download Defaults

on: workflow_dispatch

jobs:
  setup-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Commands in Codespace
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}  # The same repository
          path: .github/workflows  # The path to the workflow files

      - name: Install Dependencies and Build
        run: |
          # Add execute permission to make tests.
          sudo chmod a+x Makefile config-variables.sh data-test extract-full-data.sh 
          
          # Get the name of the newly created repository
          repo_name=$(basename "${{ github.repository }}")
          
          # Change to the project directory
          cd "/workspaces/$repo_name"

          # Install default dependencies
          echo yes | echo sudo | sudo cpan App::cpanminus
          sudo cpanm CGI
