name: Create Action
run-name: ${{github.actor}} ran
on: [create]
jobs:
  No-Hand-Holding:
    runs-on: ubuntu-latest
    steps:
      - run: echo ran
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls -a
      - run: echo ${{github.repository}} ----------------
      - name: only repo name
        run: |
          _curRepo=${{github.repository}}
          _repoName="${_curRepo##*/}"
          echo $_repoName ------------------
          sed "s/_testResultRepo=\"roffit-pull-diff\"/_testResultRepo=\"$_repoName\"/" config-variables.sh
      - name: Complete
        run: |
          echo it worked
          echo abc > abc.txt
          cat abc.txt
          sed -i "s/abc/xyz/" abc.txt
          cat abc.txt
          echo it worked
      - name: Finish
        run: |
          echo worked. Next real draft.
