name: Update Template Variable

on:
  repository:
    types:
      - created

jobs:
  update-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Template Variable
        run: |
          repo_name="${{ github.repository }}"
          echo "Updating template variable to $repo_name"
          sed -i "s/_testResultRepo=\"roffit-pull-diff\"/_testResultRepo=\"$repo_name\"/" config-variables.sh          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update template variable"
          git push origin HEAD
